### ISSUE TITLE
install problem with google colab

### ISSUE THREAD

**Issue by chengheben** [psychNerdJae/hddm_tutorial#1]
Hi Jae, 
    I am a starter in using hddm. When I follow your tutorial in colab, it failed. I install pymc and kabuki successfully, but hddm failed. 

The error went like:
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

do you know how to solve the problem?

**Comment by psychNerdJae** [comment]
Hi, thanks for your note. I don't know off the top of my head what the underlying issue could be, but it looks like there's possibly something about a newer version of HDDM that breaks the installation process in a colab notebook. I spent some time trying to see whether I could modify the colab environment (e.g., by downgrading the Python installation to 3.6) to make the code run as-is, but it's not looking great.

I'll also note that since the writing of this tutorial many years ago, the developers have put out a new package called [HSSM](https://github.com/lnccbrown/HSSM), which supersedes HDDM. I should probably update this tutorial series at some point to reflect that, but I'll also note that HSSM comes with built-in datasets and [new tutorials](https://lnccbrown.github.io/HSSM/getting_started/getting_started/) written by the developers themselves, which you might find useful!

Unfortunately, I'm in the midst of dissertation-writing, so I don't have quite the mental bandwidth needed to look into this further. But hopefully, the HSSM materials will provide all the information you'll need to learn about using sequential sampling models – I've always found their documentation very helpful!
